"use client";

import { useMemo, useState } from "react";

type Item = { id: string; title: string; category: string; summary: string; meta?: string };
const ITEMS: Item[] = [{ id: "1", title: "Bangkok skyline", category: "Travel", summary: "Golden hour rooftop.", meta: "2026" }];
const CATEGORIES = ["All", "Travel", "Work"];

function SkylineProof() { return <svg viewBox="0 0 900 540" role="img" aria-label="Authored line drawing of a Bangkok skyline at golden hour"><rect width="900" height="540" fill="#263029" /><path d="M0 392h900" stroke="#d9de66" strokeWidth="2" opacity=".7" /><path d="M44 392V282h42v110m10 0V238h58v154m15 0V303h34v89m22 0V184h74v208m18 0V266h45v126m18 0V220h54v172m18 0V291h31v101m16 0V166h83v226m17 0V247h52v145m14 0V281h77v111m15 0V210h44v182m18 0V257h63v135" fill="none" stroke="#f1eadb" strokeWidth="4" /><path d="M0 444c180-28 300-10 450 5s274 15 450-12" fill="none" stroke="#8c9683" strokeWidth="2" /><circle cx="710" cy="118" r="45" fill="#d9de66" opacity=".9" /><g stroke="#8c9683" strokeWidth="1" opacity=".55">{Array.from({ length: 7 }, (_, i) => <path key={i} d={`M${30 + i * 125} 42v452`} />)}</g></svg>; }

export default function Home() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const list = useMemo(() => ITEMS.filter((item) => (category === "All" || item.category === category) && `${item.title} ${item.summary} ${item.category}`.toLowerCase().includes(query.toLowerCase())), [category, query]);
  return <div className="darkroom"><main className="photo-shell"><nav className="photo-nav"><span className="photo-wordmark">PHOTO / CONTACT SHEET</span><span>Field archive · proof scale</span></nav><header className="photo-hero"><div><h1>Hold the light long enough to remember.</h1><p>A visual notebook for scenes, places, and fragments worth keeping. The archive is intentionally small while its source material is still being collected.</p></div><div className="archive-meta"><strong>{ITEMS.length}</strong> verified frame<br />{CATEGORIES.length - 1} shelves in the index</div></header><section className="archive-tools" aria-label="Photo archive filters"><span className="filter-label">Archive / browse</span><input className="search-field" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search frames" aria-label="Search frames" /><div className="filter-tabs">{CATEGORIES.map((item) => <button key={item} type="button" className={`filter-tab ${category === item ? "is-active" : ""}`} onClick={() => setCategory(item)}>{item}{item === "Work" ? " · empty" : ""}</button>)}</div></section>{list.length ? <section className="contact-sheet" aria-label="Photo proof sheet">{list.map((item) => <div className="proof-frame" key={item.id}><div className="proof-image"><SkylineProof /></div><div className="proof-caption"><span className="proof-label">{item.category} / {item.meta}</span><h2>{item.title}</h2><p>{item.summary}</p><dl><div><dt>Status</dt><dd>Verified metadata</dd></div><div><dt>Image asset</dt><dd>Not attached</dd></div></dl></div></div>)}</section> : <p className="empty-archive">No frames match this shelf yet. “Work” is an intentional empty category until a verified image is added.</p>}<footer className="photo-footer">The skyline is an authored proof drawing because this portfolio repository currently has no attached photo asset. It is not presented as a documentary photograph.</footer></main></div>;
}
